services:
  api:
    build: ./api
    container_name: re-chatty-api

    ports:
      - "3000:3000"

    env_file:
      - ./api/.env

    restart: always

  ui:
    build:
      context: ./ui
      secrets:
        - env
    container_name: re-chatty-ui

    ports:
      - "5173:80"

    depends_on:
      - api

    restart: always

secrets:
  env:
    file: ./ui/.env
