name: Deploy re-chatty

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1

  ECS_CLUSTER: re-apps-cluster
  ECS_SERVICE: re-chatty-td-service-latest

  ECR_FRONTEND_REPOSITORY: re-chatty/ui
  ECR_BACKEND_REPOSITORY: re-chatty/api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Frontend
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/re-chatty/ui:${{ github.sha }} \
            ./ui

      - name: Build Backend
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/re-chatty/api:${{ github.sha }} \
            ./api

      - name: Push Frontend
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/re-chatty/ui:${{ github.sha }}

      - name: Push Backend
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/re-chatty/api:${{ github.sha }}

      - name: Download Current Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition re-chatty-td \
            --query taskDefinition \
            > task-definition.json

      - name: Update Frontend Image
        id: frontend-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ui
          image: ${{ steps.login-ecr.outputs.registry }}/re-chatty/ui:${{ github.sha }}

      - name: Update Backend Image
        id: backend-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.frontend-task.outputs.task-definition }}
          container-name: api
          image: ${{ steps.login-ecr.outputs.registry }}/re-chatty/api:${{ github.sha }}

      - name: Deploy ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.backend-task.outputs.task-definition }}
          service: re-chatty-td-service-latest
          cluster: re-apps-cluster
          wait-for-service-stability: true
